// resources/js/ui/app.tsx
import axios from 'axios';
import { PageStaticData } from './App.d';
import React, { useState, useEffect } from "react";

import { Router } from './router/index';
import { Footer } from './components/Footer/Footer';
import { Navbar } from './components/Navbar/Navbar';

export const App = () => {

    const [pageStatics, setPageStatics] = useState<PageStaticData>();
    
    const getPageStatics = () => {
        axios.get('/api/page-statics')
            .then((response) => {
                setPageStatics(response.data);
            })
            .catch((error) => {

            });
    };

    useEffect(() => {
        getPageStatics();
    });

    return (
        <>
            {typeof pageStatics != 'undefined' ? (
                <Navbar logo={pageStatics?.logo} footer={pageStatics?.footer}/>
            ): (
                <div></div>
            )}
            <Router />
            {typeof pageStatics != 'undefined' ? (
                <Footer logo={pageStatics?.logo} footer={pageStatics?.footer}/>
            ): (
                <div></div>
            )}
        </>
    );
};

// resources/js/ui/App.vue
<template>
    <div v-if="initRender">
        <Navbar :staticData="pageStaticData.header"/>
        <router-view />
        <Footer :logo="pageStaticData.logo" :staticData="pageStaticData.footer" />
    </div>
</template>

<script>
    import axios from 'axios';
    import { ref, reactive, onMounted, computed } from 'vue';

    import Navbar from './components/Navbar/Navbar';
    import Footer from './components/Footer/Footer';

    export default {
        name: "Ui",

        components: {
            Navbar,
            Footer
        },

        setup() {
            const pageStaticData = ref();
            const initRender = ref(false);

            const getPageStatics = () => {
                axios.get('/api/page-statics')
                    .then((response) => {
                        pageStaticData.value = response.data;
                        initRender.value = true;
                    })
                    .catch((error) => {

                    });
            }

            onMounted(() => {
                getPageStatics()
            });

            return {
                initRender,
                pageStaticData
            }
        }
    };
</script>
